[package]
name = "juiz_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json="1.0.108"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
signal-hook = "0.3.17"
libloading = "0.8.1"
thiserror = "1.0.50"
mopa = "0.2.2"
tokio = { version = "1.35.0", features = ["full"] }
regex = "1.7.0"
serde = "1.0.193"
axum = "0.7.2"
uuid = "1.6.1"
futures = "0.3.29"
opencv = {version="0.88.6", features=["clang-runtime"]}


# example_container = { path="container_examples/example_container" }

[workspace]
members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec", 
    "brokers/http_broker",
    "examples/container_examples",
    "examples/increment_process",
    "examples/container_examples/example_container",
    "examples/container_examples/example_container_get",
    "examples/container_examples/example_container_increment",
    "examples/opencv_examples/cv_camera_container",
    "examples/opencv_examples/cv_camera_capture",
]
default-members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec",
    "brokers/http_broker",
    "examples/container_examples",
    "examples/increment_process",
    "examples/container_examples/example_container",
    "examples/container_examples/example_container_get",
    "examples/container_examples/example_container_increment",
    "examples/opencv_examples/cv_camera_container",
    "examples/opencv_examples/cv_camera_capture",
]