[package]
name = "juiz_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
serde = {version = "1.0.193", features = ["derive"]}
serde_json="1.0.108"
yaml-rust2 = "0.8.0"

anyhow = "1.0.75"
thiserror = "1.0.50"
log = "0.4.20"
env_logger = "0.10.1"

regex = "1.7.0"
hashlink = "0.8"
home = "0.5.9"

signal-hook = "0.3.17"

libloading = "0.8.1"
mopa = "0.2.2"

tokio = { version = "1.38.0", features = ["full"] }
axum = "0.7.2"
uuid = "1.6.1"
futures = "0.3.29"

interprocess = {version="2.2.0", features=["tokio"]}

# opencv = {version="0.84.0", default-features=false, features=["clang-runtime"]}
opencv = {version="0.92.0", default-features=false, features=["imgproc", "imgcodecs", "clang-runtime"]}
image = "0.24.0"
# cv-convert = {version="0.25.0", default-features=false, features=["opencv_0-84", "image_0-24"]}

num-traits = "0.2.19"
nalgebra = "0.32.5"
quaternion-core = "0.5.0"
approx = "*"
# example_container = { path="container_examples/example_container" }

pyo3 = {version = "0.22.1", features=["auto-initialize", "gil-refs"]}

[workspace]
members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec", 
    "ecs/main_loop_ec",
    "brokers/http_broker",
    #"examples/rust/container",
    "examples/rust/process/increment_process",
    "examples/rust/process/decrement_process",
    "examples/rust/container/example_container",
    "examples/rust/container/example_container_get",
    "examples/rust/container/example_container_increment",
    "examples/rust/opencv_examples/juiz_opencv",
    #"examples/python/python_container", 
]
default-members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec", 
    "ecs/main_loop_ec",
    "brokers/http_broker",
    # "examples/rust/container",
    #"examples/rust/process/increment_process",
    #"examples/rust/process/decrement_process",
    "examples/rust/container/example_container",
    "examples/rust/container/example_container_get",
    "examples/rust/container/example_container_increment",
    "examples/rust/opencv_examples/juiz_opencv",
]
