[package]
name = "juiz_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json="1.0.108"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
signal-hook = "0.3.17"
libloading = "0.8.1"
thiserror = "1.0.50"
mopa = "0.2.2"
tokio = { version = "1.35.0", features = ["full"] }
regex = "1.7.0"
serde = "1.0.193"
axum = "0.7.2"
uuid = "1.6.1"
futures = "0.3.29"
opencv = {version="0.84.0", default-features=false, features=["clang-runtime"]}
image = "0.24.0"
cv-convert = {version="0.25.0", default-features=false, features=["opencv_0-84", "image_0-24"]}

# example_container = { path="container_examples/example_container" }

[workspace]
members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec", 
    "brokers/http_broker",
    "examples/container_examples",
    "examples/increment_process",
    "examples/container_examples/example_container",
    "examples/container_examples/example_container_get",
    "examples/container_examples/example_container_increment",
    "examples/opencv_examples/juiz_opencv",
#   "examples/opencv_examples/cv_filesystem",
#    "examples/opencv_examples/cv_filesystem_imsave",
    "examples/opencv_examples/cv_capture_system",
]
default-members = [
    ".",
    "app/juiz_command",
    "ecs/timer_ec",
    "ecs/one_shot_ec",
    "brokers/http_broker",
    "examples/container_examples",
    "examples/increment_process",
    "examples/container_examples/example_container",
    "examples/container_examples/example_container_get",
    "examples/container_examples/example_container_increment",
    "examples/opencv_examples/juiz_opencv",
    "examples/opencv_examples/cv_capture_system",
]