[package]
name = "juiz_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json="1.0.108"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
signal-hook = "0.3.17"
libloading = "0.8.1"
thiserror = "1.0.50"
mopa = "0.2.2"
tokio = "1.35.0"

serde = "1.0.193"
axum = "0.7.2"
uuid = "1.6.1"
futures = "0.3.29"
utoipa-swagger-ui = { version = "5.0.0", features = ["axum"] }
utoipa-redoc = { version="2.0.0", features = ["axum"] }
utoipa-rapidoc = { version="2.0.0", features = ["axum"] }
utoipa = { version="4.1.0", features = ["axum_extras"] }
# serde_json = { path="./json" }

# example_container = { path="container_examples/example_container" }

[workspace]
members = [
    "timer_ec",
    "http_broker",
    "container_examples",
    "increment_process",
    "container_examples/example_container",
    "container_examples/example_container_get",
    "container_examples/example_container_increment",
]
default-members = [
    "timer_ec",
    "http_broker",
    "container_examples",
    "increment_process",
    "container_examples/example_container",
    "container_examples/example_container_get",
    "container_examples/example_container_increment",
]