[package]
name = "juiz_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json="1.0.108"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
signal-hook = "0.3.17"
libloading = "0.8.1"
# serde_json = { path="./json" }
