services:
  rust_juiz:
    #restart: always
    container_name: juiz
    image: rust_juiz
    # command: bash /code/start_server_dummy_docker.sh 
    working_dir: /code
    volumes:
      - .:/code
    # ports:
    #   - "8081:8081"
    environment: 
      - USER=user
    #  - OTEL_SERVICE_NAME=yagura
    #  - OTLP_GRPC_ENDPOINT=jaeger-collector:4317
    #  - OTEL_PYTHON_LOG_CORRELATION=true
    #  - OTEL_PYTHON_LOG_LEVEL=debug
    #  - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true