"name": "test_system"
"plugins":
  "components": 
      "rust_integer_component":
          "language": "rust"
          "path": "../target/debug"
"containers":
  - "type_name": "rust_integer_container"
    "name": "container0"
    "processes": 
      - "type_name": "rust_integer_container_get"
        "name" : "get0"
      - "type_name": "rust_integer_container_set"
        "name" : "set0"