name: talker_listener
option:
  http_broker:
    start: true
    port: 8000
plugins:
  process_factories:
    rust_talker:
      path: "../target/debug"
    rust_listener:
      path: "../target/debug"
processes:
  - type_name: rust_talker
    name: talker0
  - type_name: rust_listener
    name: listener0
connections:
  - name: con0
    connection_type: Push
    source: 
      name: talker0
      type_name: rust_talker
    destination:
      name: listener0
      type_name: rust_listener
    arg_name: arg1
ecs:
  - name: ec0
    type_name: main_loop_ec
    rate: 1.0
    bind:
      - name: talker0
        type_name: rust_talker
    auto_start: true