all: 
	cd example_container; make
	cd example_container_get; make
	cd example_container_increment; make

clean:
	cd example_container; make clean
	cd example_container_get; make clean
	cd example_container_increment; make clean
