[package]
name = "juiz_command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
juiz_core = { path="../../" }
structopt = "0.3.26"
home = "0.5.9"
clap = { version="4.4.10", features = ["derive"] }
