"name": "test_system"
"option":
  "http_broker":
    "start": true
    "port": 8080
"plugins":       
  "components": 
      "imgproc_component":
          "language": "rust"
          "path": "./target/debug"
"containers":
  - "type_name": "imgproc_component_container"
    "name": "container0"
    "processes": 
      - "type_name": "imgproc_component_container_capture_image"
        "name" : "capture_image0"
      #- "type_name": "imgproc_component_container_get_image"
      #  "name" : "get_image0"
