"name": "test_system"
"plugins":
  "components": 
      "python_integer_component":
          "language": "python"
          "path": "../"
"containers":
  - "type_name": "python_integer_container"
    "name": "container0"
    "processes": 
      - "type_name": "python_integer_container_get"
        "name" : "get0"
      - "type_name": "python_integer_container_set"
        "name" : "set0"