
#[derive(Debug, PartialEq)]
#[repr(C)]
pub enum JuizError {
    GeneralError,
    ProcessManifestError,
    ArgumentMissingError,
    ArgumentMissingWhenCallingError,
    ArgumentIsNotObjectError,
    ArgumentManifestIsInvalidError,
    NotImplementedError,
    ProcessCanNotFoundError,
    ManifestNameMissingError,
    ManifestTypeNameMissingError,
    ManifestArgumentsMissingError,
    ManifestArgumentsInvalidError,
    ManifestArgumentDefaultValueMissingError,
    ArgumentTypeIsNotStringError,
    ArgumentTypeIsNotMatchWithDefaultError,
    ManifestArgumentDefaultValueIsInvalidTypeError,
    ProcessOutputMemoIsNotInitializedError,
    ArgumentDescriptionIsNotStringError,
    SourceConnectionCanNotBorrowMutableProcessReferenceError,
    DestinationConnectionCanNotBorrowMutableProcessReferenceError,
    ValueAccessValueIsNotObjectError,
    ValueAccessKeyNotFoundError,
    ValueAccessValueIsNotStrError,
    ConnectionBuilderCanNotBorrowSourceProcessError,
    ConnectionBuilderCanNotBorrowDestinationProcessError,
    ProcessRackCanNotBorrowInsertedProcessError,
    CoreBrokerCanNotLockProcessMutexError,
    SourceConnectionNewReceivedInvalidManifestTypeError,
    DestinationConnectionNewReceivedInvalidManifestTypeError,
    ProcessFactoryOfSameTypeNameAlreadyExistsError,
    ProcessFactoryCanNotFoundByTypeNameError,
    ManifestIsNotObjectError {  },
    ManifestTypeNameIsNotStringError {  },
    ManifestDoesNotIncludeTypeNameError {  },
    CoreStoreCanNotLockProcessFactoryError {  },
    CoreBrokerCanNotLockProcessFactoryMutexError {  },
    CoreBrokerCanNotInsertProcessError {  },
    PluginLoadFailedError {  },
    ProcesssFactoryCanNotLockError {  },
    ManifestIsNotStringError {  },
    ManifestDoesNotContainsKeyError {  },
    ManifestIsNotArrayError {  },
    ProcessFactoryWrapperCanNotLockProcessFactoryError {  },
    MutexLockFailedError {  },
    ManifestDoesNotIncludeKeyError {  },
}


