[package]
name = "sss_arg_proc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]
path="src/lib.rs"


[dependencies]
juiz_sdk = { path = "../../../juiz_sdk/" }
