all:
	cd increment_process; make
	cd decrement_process; make
	cd talker_cpp; make
	cd listener_cpp;make 
clean:
	cd increment_process; make clean
	cd decrement_process; make clean
	cd talker_cpp; make clean
	cd listener_cpp; make clean