all: 
	cd cpp_container; make
	cd cpp_container_get; make
	cd cpp_container_increment; make

clean:
	cd cpp_container; make clean
	cd cpp_container_get; make clean
	cd cpp_container_increment; make clean
