"name": "test_system"
"plugins":
  "broker_factories": 
    "qmp_broker":
      "path": "./target/debug"           
  "process_factories":
    "increment_process":
      "path": "./target/debug"
"brokers":
  - "type_name": "qmp"
    "name": "localhost_server"
    "host": "0.0.0.0"
    "port": 5000
#  - "type_name": "ipc"
#    "name": "juiz.sock"
"processes":
  - "type_name": "increment_process"
    "name": "increment0" 
